server.port=8080
spring.application.name=url-shortener

spring.data.mongodb.host=<host>
spring.data.mongodb.port=<port>
spring.data.mongodb.database=<database>
spring.data.mongodb.auto-index-creation=true

