server.port=8080
spring.application.name=url-shortener

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=shortenerdb
spring.data.mongodb.auto-index-creation=true

