services:
  mysql:
    container_name: 'url-shortener-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=url_db'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD=123'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'